### PR TITLE
translated welcome/welcome-to-d.md

### PR DESCRIPTION
**Pull request by kotet**
> _high level_ constructs for great modeling power

I could not be translateed only this sentence in the lack of knowledge.

### CODE REVIEW

**Comment by wilzbach** [comment]
@kotet thanks a lot for your work!

> I could not be translateed only this sentence in the lack of knowledge.

That's why it may be worthwhile to wait for the feedback from someone of @dlang-tour/japanese -  you are not alone on this mission ;-)
Also @dlang-tour/japanese there is no rule to communicate in English only, feel free to use whatever you are comfortable with. 

Btw for the other languages we try to find someone else from the translation team that can read through the translation and check that it's understandable without the English original. In other words this means that we want to encourage you to not approve your translation yourself.  Does this sound reasonable?

**Comment by kotet** [comment]
> we want to encourage you to not approve your translation yourself.

I feel the same way. We need reviewer. I think @simdnyan and @alphaKAI who are @dlang-tour/japanese member is the right person. If they are busy, I will try asking my friend.

@simdnyan @alphaKAI 忙しくなければレビューをしてくれませんか?

**Comment by alphaKAI** [comment]
> high level constructs for great modeling power
> 強力な表現を可能にする高級な構文
> と解釈しましたがどうでしょう?

**Comment by kotet** [comment]
多分そんなような意味ですよね、でもあんまり自信がなくて……
どこかに似た文の対訳とかがあればいいんですけどなかなか見つけられない

**Comment by kotet** [comment]
@wilzbach [O-Bean](https://github.com/O-Bean) undertook the review. He is Japanese speaker. He can correct the mistakes of Japanese. However, he has no knowledge of programming. What does 

> check that it's understandable

mean?

**Comment by wilzbach** [comment]
>  O-Bean undertook the review. He is Japanese speaker. He can correct the mistakes of Japanese. 

Awesome! Invitation is out. I think the GitHub web UI is usable without programming experience?

> However, he has no knowledge of programming.

Maybe he learns a bit ;-)

> What does check that it's understandable

Oh my point was that during the translation it can easily happen (at least for German and Russian) that the structure of the English version is kept, so that it sounds very strange to a native speaker.
In other words the point of reviewing is to achieve a good quality, s.t. a reader doesn't quit after the second page.

**Pull request merged**
