### PR TITLE
translated welcome/run-d-program-locally.md

### PR DESCRIPTION
**Pull request by kotet**

### CODE REVIEW

**Comment by wilzbach** [comment]
I play random Japanese reviewer roulette and assign @alphaKAI to review this PR. Would you be so kind to act as a second pair of eyes on this translation? :)

(please reassign if you are busy at the moment)

**Comment by kotet** [comment]
@wilzbach Excuse me, can I use this PR for O-Bean's practice?

**Comment by wilzbach** [comment]
> @wilzbach Excuse me, can I use this PR for O-Bean's practice?

Oh I didn't know that. Sure why not?

FYI

image

**Comment by kotet** [comment]
Ok, thanks.

**Pull request merged**
