### PR TITLE
translated basics/imports-and-modules.md

### PR DESCRIPTION
**Pull request by kotet**

### CODE REVIEW

**Comment by wilzbach** [comment]
Japanese reviewer roulette: @alphaKAI would you have time to look at this translation on your convenience? (no pressure!)

**Comment by alphaKAI** [comment]
Ok, I'll review it. I didn't check the notifications.

**Comment by alphaKAI** [comment]
I think, statement → ステートメント, is not exactly translation.
Use `文` instead of `ステートメント`.

By the way, this commit is seemed outdated, for original(English) version is updated thus this contains a translated text for deleted text in latest English version.
This pull request should follow the original update.

**Comment by kotet** [comment]
I reflected your review. Does it make sence?

**Comment by alphaKAI** [comment]
Yes, it does. LGTM, I merge this pull request.

**Pull request merged**
