### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by KisaragiEffective**

### CODE REVIEW

**Comment by kubo39** [comment]
@KisaragiEffective 
Unfortunately travis ci won't run immediately (or never). I guess this commit doesn't break anything so could you please add `[skip travis]` on your commit and force-push?
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by KisaragiEffective** [comment]
@kubo39 
Okay, I think it's done.

**Comment by kubo39** [comment]
Hmm, I have no rights to change the settings... cc @kotet

**Comment by kubo39** [comment]
Thank you!

**Pull request merged**
